# Config file of seada-alert

# Folder that contains the alarm's rule yaml files
# Any .yaml file will be loaded as a rule
alerts_folder: alerts

# Sleep interval time between search process in seconds
#sleep_interval: 300 #seconds
sleep_interval: 60 #seconds

# ElasticSearch config
es_host: localhost
es_port: 9200


